List p = 18f4520
    #include<p18f4520.inc>
    CONFIG OSC = INTIO67
    CONFIG WDT = OFF
    org 0x00 ; PC = 0x00
    initial:
	MOVLW 0x03 ; WREG = 0x08
	MOVWF TRISA ; TRISA = WREG
	MOVLW 0x0F ; WREG = 0x0B
	MOVWF TRISB ; TRISB = WREG
	CLRF TRISC
    start:
	MOVF TRISA, WREG
	BTFSC TRISB, 0 ; Check TRISB[0] == 1?
	ADDWF TRISC, f
	RLNCF TRISA, f
	RRNCF TRISB, f
	MOVF TRISA, WREG
	BTFSC TRISB, 0 ; Check TRISB[0] == 1?
	ADDWF TRISC, f
	RLNCF TRISA, f
	RRNCF TRISB, f
	MOVF TRISA, WREG
	BTFSC TRISB, 0 ; Check TRISB[0] == 1?
	ADDWF TRISC, f
	RLNCF TRISA, f
	RRNCF TRISB, f
	MOVF TRISA, WREG
	BTFSC TRISB, 0 ; Check TRISB[0] == 1?
	ADDWF TRISC, f
	RLNCF TRISA, f
	RRNCF TRISB, f
    
    end